# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: linux_machine.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13linux_machine.proto\x12\rlinux_machine\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"!\n\x0f\x43ommandResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2Z\n\x0cLinuxMachine\x12J\n\x07\x45xecute\x12\x1d.linux_machine.CommandRequest\x1a\x1e.linux_machine.CommandResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'linux_machine_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMANDREQUEST._serialized_start=38
  _COMMANDREQUEST._serialized_end=71
  _COMMANDRESPONSE._serialized_start=73
  _COMMANDRESPONSE._serialized_end=106
  _LINUXMACHINE._serialized_start=108
  _LINUXMACHINE._serialized_end=198
# @@protoc_insertion_point(module_scope)
