# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import remote_control_pb2 as remote__control__pb2


class RemoteControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecCmd = channel.unary_unary(
                '/remote_control.RemoteControl/ExecCmd',
                request_serializer=remote__control__pb2.CmdRequest.SerializeToString,
                response_deserializer=remote__control__pb2.CmdResponse.FromString,
                )


class RemoteControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecCmd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecCmd': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecCmd,
                    request_deserializer=remote__control__pb2.CmdRequest.FromString,
                    response_serializer=remote__control__pb2.CmdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remote_control.RemoteControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RemoteControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecCmd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote_control.RemoteControl/ExecCmd',
            remote__control__pb2.CmdRequest.SerializeToString,
            remote__control__pb2.CmdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
